
import random

first = list()
first.append("	traditional	")
first.append("	poor	")
first.append("	southern	")
first.append("	areful	")
first.append("	united	")
first.append("	different	")
first.append("	tiny	")
first.append("	former	")
first.append("	exciting	")
first.append("	important	")
first.append("	every	")
first.append("	consistent	")
first.append("	useful	")
first.append("	aggressive	")
first.append("	massive	")
first.append("	administrative	")
first.append("	automatic	")
first.append("	successfully	")
first.append("	tall	")
first.append("	inner	")
first.append("	well-off	")
first.append("	secretive	")
first.append("	frightening	")
first.append("	empty	")
first.append("	pleasant	")
first.append("	frightening	")
first.append("	woozy	")
first.append("	laughable	")
first.append("	ossified	")
first.append("	wandering	")
first.append("	brainy	")
first.append("	yummy	")
first.append("	elfin	")
first.append("	long-term	")
first.append("	toothsome	")
first.append("	miscreant	")
first.append("	homely	")
first.append("	abaft	")
first.append("	halting	")
first.append("	chivalrous	")
first.append("	substantial	")
first.append("	psychotic	")
first.append("	momentous	")
first.append("	juicy	")
first.append("	exultant	")
first.append("	rampant	")
first.append("	mundane	")
first.append("	doubtful	")
first.append("	fascinated	")
first.append("	salty	")
first.append("	previous	")
first.append("	pointless	")
first.append("	whispering	")
first.append("	halting	")
first.append("	lame	")
first.append("	nonstop	")

def get_adjective(list):
    # sort_list(second)
    return random.choice(list)