import random




noun_list = list()
noun_list.append("Doubt")
noun_list.append("Homeland")
noun_list.append("Marsh")
noun_list.append("Tilt")
noun_list.append("Piss")
noun_list.append("Meaning")
noun_list.append("Omnivore")
noun_list.append("Cloth")
noun_list.append("Vignette")
noun_list.append("Nerve")
noun_list.append("Chutney")
noun_list.append("Communication")
noun_list.append("Dinner")
noun_list.append("Lode")
noun_list.append("Perch")
noun_list.append("Permit")
noun_list.append("Reciprocity")
noun_list.append("Step	")
noun_list.append("Stimulation	")
noun_list.append("Wetsuit	")
noun_list.append("Coin	")
noun_list.append("Cook")
noun_list.append("Eggnog")
noun_list.append("Headline")
noun_list.append("Journal")
noun_list.append("Pimp")
noun_list.append("Pint")
noun_list.append("Shoemaker")
noun_list.append("Survey")
noun_list.append("Timeout")
noun_list.append("Author")
noun_list.append("Breadcrumb")
noun_list.append("Canvas")
noun_list.append("Colleague")
noun_list.append("Grandmom")
noun_list.append("Jackal")
noun_list.append("Length")
noun_list.append("Original")
noun_list.append("Spectrograph")
noun_list.append("Webinar")
noun_list.append("Assembly")
noun_list.append("Bayou")
noun_list.append("Homonym")
noun_list.append("Middle")
noun_list.append("Parenting")
noun_list.append("Pirate")
noun_list.append("Princess")
noun_list.append("Reservoir")
noun_list.append("Scholar")
noun_list.append("Steel")

noun_list.append("Silence")
noun_list.append("Fox")
noun_list.append("Owl")
noun_list.append("Firehouse")
noun_list.append("INSERT TITLE")

noun_list.append("Salesmen")
noun_list.append("Reflection")
noun_list.append("Prostitue")
noun_list.append("Skybox")
noun_list.append("Print")

noun_list.append("	salvage	")
noun_list.append("	fancy	")
noun_list.append("	damaged	")
noun_list.append("	weave	")
noun_list.append("	cars	")
noun_list.append("	hop	")
noun_list.append("	stingy	")
noun_list.append("	question	")
noun_list.append("	trees	")
noun_list.append("	complete	")
noun_list.append("	boundary	")
noun_list.append("	quarrelsome	")
noun_list.append("	sew	")
noun_list.append("	carve	")
noun_list.append("	cling	")
noun_list.append("	internal	")
noun_list.append("	callous	")
noun_list.append("	scam	")
noun_list.append("	shed	")
noun_list.append("	feel	")
noun_list.append("	literate	")
noun_list.append("	needless	")
noun_list.append("	lyrical	")
noun_list.append("	oven	")
noun_list.append("	shiver	")
noun_list.append("	quarrel	")
noun_list.append("	outstanding	")
noun_list.append("	jump	")
noun_list.append("	grandiose	")
noun_list.append("	few	")
noun_list.append("	stew	")
noun_list.append("	selfish	")
noun_list.append("	occupy	")
noun_list.append("	dump	")
noun_list.append("	simple	")
noun_list.append("	building	")
noun_list.append("		")
noun_list.append("		")
noun_list.append("		")
noun_list.append("		")


def sort_list(list):
    list.strip(" ")

def get_noun(list):
    # sort_list(second)
    return random.choice(list)