

magic_sentences = list()

magic_sentences.append("    The Longest Night she ever knew")
magic_sentences.append("By night or by water there's really little purpose")
magic_sentences.append("The cusp of cliche that speaks smaller volumes than  you think")
magic_sentences.append("God is only as mmighty as the weakest link")
magic_sentences.append("spend your whole life living for the worst thing you've ever done")
magic_sentences.append("ask me questions, wait for a second, then get the text back")
magic_sentences.append("I do you though, just so you know, if that makes it easier")


trust_is_a_closed_book = list()
trust_is_a_closed_book.append("hightlights froom work until     midnight")
trust_is_a_closed_book.append("stood up with cardboard so the wind an the rain hurts")
trust_is_a_closed_book.append("Sullen keepsakes from houses and homes of the death")
trust_is_a_closed_book.append("you say you're not listening, but I can hear you shift in the air")
trust_is_a_closed_book.append("If only we could append a symbol to the dartboard")
trust_is_a_closed_book.append("Throwing keys at holes hoping one, just one, to click")
trust_is_a_closed_book.append("Bursting open isn't the point of regret, told by riddley scott")
trust_is_a_closed_book.append("Is this where you operate? Where you click hands and ears")
trust_is_a_closed_book.append("Animals were left in the desert for bland and dumb reasons")
trust_is_a_closed_book.append("Cant catch a cold if you're moving   to      fast")
trust_is_a_closed_book.append("Craddle of ten tons, crush a car or an elephant with pressure")

Pulled_fire = list()
Pulled_fire.append("Account for yourself so you cant be caught with stolen bitcoin")
Pulled_fire.append("Not a simple push, but a flat out thrust through the air")
Pulled_fire.append("Done at an airport, where they take the bottoms of your shoes")
Pulled_fire.append("It's nothing like us, we were weaker and higher in the middle of the night")
Pulled_fire.append("Not the fish in the silk stream, but the entire internet sea of danger")
Pulled_fire.append("You ask to be called something else, as long as it's louder than the metro")
Pulled_fire.append("Ghastly burdens and sharp witted soilders, the kind that weigh your stomach down")
Pulled_fire.append("Ecigs that blow up in your pants and stain entire entryways")
Pulled_fire.append("Shorter acting pain killers, eating away at the esophageal linging")
Pulled_fire.append("I keep telling her all she needs is xanax")
Pulled_fire.append("The car pulls away and I regret not looking back one last time")

Done_and_over = list()
Done_and_over.append("Just a taste of pulled bones, your mouth harbors dust")
Done_and_over.append("If you only could catch cold")
Done_and_over.append("Sunrise over taunt mountains and gold")
Done_and_over.append("Call upstairs and see if they'll hold you like I cant")


Cash_out_with_half = list()
Cash_out_with_half.append("At least she seems to be")
Cash_out_with_half.append("While Yesterday she sowed more than she planted")
Cash_out_with_half.append("Confess on the street side, she never walked right anyway")
Cash_out_with_half.append("She'll get out of rehab and makes the Olympians shake")
Cash_out_with_half.append("She wants to leave a few days early, against medical advice.")

Wooden_Lawyer_Table = list()
Wooden_Lawyer_Table.append("She plays that old game and pulls off flower pettles with her index and thumb ")
Wooden_Lawyer_Table.append("Can't set the table when there's nothing to actually eat")
Wooden_Lawyer_Table.append("The offices of slick surfaces and a ripe plastic smelll")
Wooden_Lawyer_Table.append("Never catch your own pants down to a lawyer")

Rescue = list()
Rescue.append("She plays the oldest record and turns off the night")
Rescue.append("Ghosts from VCRs and tasteless soundtracks.")
Rescue.append("She yells through her makeup, and never lets go.")
Rescue.append("And tonight the floor will be the ceiling.")