
import random

verb_list = list()
verb_list.append("		")
verb_list.append("		")
verb_list.append("		")
verb_list.append("		")
verb_list.append("		")
verb_list.append("		")
verb_list.append("		")
verb_list.append("	paint	")
verb_list.append("	preset	")
verb_list.append("	sally	")
verb_list.append("	kick	")
verb_list.append("	dive	")
verb_list.append("		")
verb_list.append("	forsake	")
verb_list.append("	cook	")
verb_list.append("	saddle	")
verb_list.append("	listen	")
verb_list.append("	contract	")
verb_list.append("	contract	")
verb_list.append("	bring	")
verb_list.append("	gaze	")
verb_list.append("	cost	")
verb_list.append("	pass	")
verb_list.append("	contradict	")
verb_list.append("	resemble	")
verb_list.append("	moan	")
verb_list.append("	appear	")
verb_list.append("	stride	")
verb_list.append("	frighten	")
verb_list.append("	crave	")
verb_list.append("	collect	")
verb_list.append("	discover	")
verb_list.append("	inhale	")
verb_list.append("	betray	")
verb_list.append("	rewind	")
verb_list.append("	drop	")
verb_list.append("	empower	")
verb_list.append("	contrast	")
verb_list.append("	collect	")
verb_list.append("	fail	")
verb_list.append("	close	")
verb_list.append("	enlarge	")
verb_list.append("	smell	")
verb_list.append("	support	")
verb_list.append("	buy	")
verb_list.append("	sway	")
verb_list.append("	smooth	")
verb_list.append("	inlay	")
verb_list.append("	converge	")
verb_list.append("	deal	")
verb_list.append("	scant	")
verb_list.append("	caress	")
verb_list.append("	string	")
verb_list.append("	distribute	")
verb_list.append("	sever	")
verb_list.append("	suffer	")
verb_list.append("	display	")
verb_list.append("	light	")
verb_list.append("	bash	")
verb_list.append("	rid	")
verb_list.append("	alight	")
verb_list.append("	box	")
verb_list.append("	flash	")
verb_list.append("	connote	")
verb_list.append("	contradict	")
verb_list.append("	nourish	")
verb_list.append("	erase	")
verb_list.append("	leer	")



def get_verb(list):
    # sort_list(second)
    return random.choice(list)