Get_back_on = list()
Get_back_on .append("burn")
Get_back_on .append("yearn")
Get_back_on .append("judge")
Get_back_on .append("laugh")
Get_back_on .append("Forshake")
Get_back_on .append("Coddle")
Get_back_on .append("die")
Get_back_on .append("listen")
Get_back_on .append("contract")